CREATE LOGIN monitoring
WITH PASSWORD = 'monitoring@123',
CHECK_POLICY = OFF;

USE TEST_MONITORING_DATABASE;

CREATE USER monitoring FOR LOGIN monitoring;

ALTER ROLE db_owner ADD MEMBER monitoring;


SELECT name, is_disabled
FROM sys.sql_logins
WHERE name = 'monitoring';

ALTER LOGIN monitoring
WITH PASSWORD = '123';

SELECT name
FROM sys.database_principals
WHERE name = 'monitoring';





CREATE TABLE FLOOR(
	floor_id BIGINT IDENTITY PRIMARY KEY,
	floor_name NVARCHAR(20) NOT NULL,
);
INSERT INTO FLOOR VALUES (N'FLOOR4');
INSERT INTO FLOOR VALUES (N'FLOOR15');
SELECT*FROM FLOOR;

CREATE TABLE CU(
	cu_id BIGINT IDENTITY PRIMARY KEY,
	floor_id BIGINT NOT NULL,
	cu_name NVARCHAR(20) NOT NULL,
	ip_address VARCHAR(20) NOT NULL,
	snmp_version VARCHAR(20) NOT NULL,
	snmp_community NVARCHAR(20) NOT NULL,
	snmp_port INT DEFAULT 161 NOT NULL,
	is_active BIT DEFAULT 1 NOT NULL,
);

ALTER TABLE CU
ADD CONSTRAINT FK_CU_FLOOR_FLOORID
FOREIGN KEY (floor_id)
REFERENCES FLOOR (floor_id);

ALTER TABLE CU DROP CONSTRAINT FK_CU_FLOOR_FLOORID

CREATE TABLE DISTRIBUTION_BOARD(
	db_id BIGINT IDENTITY PRIMARY KEY,
	db_name NVARCHAR(40) NOT NULL,
	floor_id BIGINT NOT NULL,
	row_db BIGINT NOT NULL,
	col_db BIGINT NOT NULL,
	status_db NVARCHAR(20) NOT NULL,
	db_note NVARCHAR(255) NULL,
);

DROP TABLE DISTRIBUTION_BOARD;


SELECT*FROM DISTRIBUTION_BOARD;

INSERT INTO DISTRIBUTION_BOARD VALUES (N'4N-1', 1, 1, 12, N'active', N'-');
INSERT INTO DISTRIBUTION_BOARD VALUES (N'4N-2', 1, 2, 12, N'active', N'-');
INSERT INTO DISTRIBUTION_BOARD VALUES (N'4N-3', 1, 3, 12, N'active', N'-');
INSERT INTO DISTRIBUTION_BOARD VALUES (N'4N-4', 1, 4, 12, N'active', N'-');
INSERT INTO DISTRIBUTION_BOARD VALUES (N'4N-5', 1, 5, 12, N'active',  N'-');
INSERT INTO DISTRIBUTION_BOARD VALUES (N'4N-6', 1, 6, 12, N'active',  N'-');
INSERT INTO DISTRIBUTION_BOARD VALUES (N'4N-7', 1, 7, 12, N'active',  N'-');
INSERT INTO DISTRIBUTION_BOARD VALUES (N'4N-8', 1, 8, 12, N'active',  N'-');


--DELETE FROM DISTRIBUTION_BOARD WHERE db_id = 8;
select floor_id from DISTRIBUTION_BOARD where floor_id = 1;

ALTER TABLE DISTRIBUTION_BOARD
ADD CONSTRAINT FK_DB_FLOOR_FLOORID
FOREIGN KEY (floor_id)
REFERENCES FLOOR (floor_id);

ALTER TABLE DISTRIBUTION_BOARD DROP CONSTRAINT FK_DB_FLOOR_FLOORID

CREATE TABLE RACK(
	rack_id BIGINT IDENTITY PRIMARY KEY,
	rack_name NVARCHAR(20) NOT NULL,
	floor_id BIGINT NOT NULL,
	row_rack BIGINT NOT NULL,
	col_rack BIGINT NOT NULL,
	status_db NVARCHAR(20) NOT NULL,
	rack_note NVARCHAR(255) NULL,
);
INSERT INTO RACK VALUES (N'4D-1', 1, 2, 1, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-2', 1, 2, 2, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-3', 1, 2, 3, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-4', 1, 2, 4, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-5', 1, 2, 5, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-6', 1, 2, 6, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-7', 1, 2, 7, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-8', 1, 2, 8, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-9', 1, 2, 9, N'active',  N'-');
INSERT INTO RACK VALUES (N'4D-10', 1, 2, 10, N'active',  N'-');

select*from RACK 
ALTER TABLE RACK
ADD CONSTRAINT FK_RACK_FLOOR_FLOORID
FOREIGN KEY (floor_id)
REFERENCES FLOOR (floor_id);

ALTER TABLE RACK DROP CONSTRAINT FK_RACK_FLOOR_FLOORID

CREATE TABLE WORKDESKS(
	workdesk_id BIGINT IDENTITY PRIMARY KEY,
	workdesk_name NVARCHAR(50) NOT NULL,
	workdesk_type NVARCHAR(50) NOT NULL,
	floor_id BIGINT NOT NULL,
	row_workdesk BIGINT NOT NULL,
	col_workdesk BIGINT NOT NULL,
	status_workdesk NVARCHAR(20) NOT NULL,
	workdesk_note NVARCHAR(255) NULL,
);
ALTER TABLE WORKDESKS
ADD CONSTRAINT FK_WORKDESKS_FLOOR_FLOORID
FOREIGN KEY (floor_id)
REFERENCES FLOOR (floor_id);

ALTER TABLE WORKDESKS DROP CONSTRAINT FK_WORKDESKS_FLOOR_FLOORID

CREATE TABLE METRIC_OUTLET(
	metric_id BIGINT IDENTITY PRIMARY KEY,
	current_ampe DECIMAL(10,3) NULL,
	voltage DECIMAL(10,3) NULL,
	floor_id BIGINT NOT NULL,
	cu_id BIGINT NOT NULL,
	db_id BIGINT NOT NULL,
	rack_id BIGINT NOT NULL,
);


---------------------------------------------------------------

CREATE TABLE DB_RACK_MAP(
	rack_id BIGINT NOT NULL,
	db_id BIGINT NOT NULL,
	PRIMARY KEY (rack_id, db_id),
);
ALTER TABLE DB_RACK_MAP
ADD CONSTRAINT FK_RACK_DB_RACK_MAP
FOREIGN KEY (rack_id)
REFERENCES RACK (rack_id);

ALTER TABLE DB_RACK_MAP
ADD CONSTRAINT FK_DB_DB_RACK_MAP
FOREIGN KEY (db_id)
REFERENCES DISTRIBUTION_BOARD (db_id);

ALTER TABLE DB_RACK_MAP DROP CONSTRAINT FK_RACK_DB_RACK_MAP
ALTER TABLE DB_RACK_MAP DROP CONSTRAINT FK_DB_DB_RACK_MAP

CREATE TABLE CU_DB_MAP(
	cu_id BIGINT NOT NULL,
	db_id BIGINT NOT NULL,
	PRIMARY KEY (cu_id, db_id),
);
ALTER TABLE CU_DB_MAP
ADD CONSTRAINT FK_CU_CU_DB_MAP
FOREIGN KEY (cu_id)
REFERENCES CU (cu_id);

ALTER TABLE CU_DB_MAP
ADD CONSTRAINT FK_DB_CU_DB_MAP
FOREIGN KEY (db_id)
REFERENCES DISTRIBUTION_BOARD (db_id);

ALTER TABLE CU_DB_MAP DROP CONSTRAINT FK_CU_CU_DB_MAP
ALTER TABLE CU_DB_MAP DROP CONSTRAINT FK_DB_CU_DB_MAP

CREATE TABLE DB_WORKDESK_MAP(
	workdesk_id BIGINT NOT NULL,
	db_id BIGINT NOT NULL,
	PRIMARY KEY (workdesk_id, db_id),
);

ALTER TABLE DB_WORKDESK_MAP
ADD CONSTRAINT FK_WORKDESK_DB_WORKDESK_MAP
FOREIGN KEY (workdesk_id)
REFERENCES WORKDESKS (workdesk_id);

ALTER TABLE DB_WORKDESK_MAP
ADD CONSTRAINT FK_DB_DB_WORKDESK_MAP
FOREIGN KEY (db_id)
REFERENCES DISTRIBUTION_BOARD (db_id);

ALTER TABLE DB_WORKDESK_MAP DROP CONSTRAINT FK_WORKDESK_DB_WORKDESK_MAP
ALTER TABLE DB_WORKDESK_MAP DROP CONSTRAINT FK_DB_DB_WORKDESK_MAP

----------



/*ALTER TABLE child_table
ADD CONSTRAINT constraint_name
FOREIGN KEY (foreign_key_column)
REFERENCES parent_table (primary_key_column);
*/

SELECT * FROM sys.dm_exec_connections WHERE local_net_address IS NOT NULL;



