CREATE LOGIN monitoring
WITH PASSWORD = 'monitoring@123',
CHECK_POLICY = OFF;

USE TEST_MONITORING_DATABASE;

--CREATE USER monitoring FOR LOGIN monitoring;

--ALTER ROLE db_owner ADD MEMBER monitoring;


SELECT name, is_disabled
FROM sys.sql_logins
WHERE name = 'monitoring';

ALTER LOGIN monitoring
WITH PASSWORD = '123';

SELECT name
FROM sys.database_principals
WHERE name = 'monitoring';


CREATE TABLE FLOOR(
	floor_id BIGINT IDENTITY PRIMARY KEY,
	floor_name NVARCHAR(20) NOT NULL,
);

SELECT*FROM FLOOR;

CREATE TABLE ZONES (
	zone_id BIGINT IDENTITY PRIMARY KEY,
	floor_id BIGINT NOT NULL,
	zone_key NVARCHAR(20) NOT NULL,
	zone_name NVARCHAR(20) NULL,
)
INSERT INTO ZONES VALUES (2,N'left', N'Left Area');
INSERT INTO ZONES VALUES (2,N'right', N'Right Area');

CREATE TABLE CU(
	cu_id BIGINT IDENTITY PRIMARY KEY,
	floor_id BIGINT NOT NULL,
	cu_index BIGINT NOT NULL,
	cu_name NVARCHAR(40) NOT NULL,
	ip_address VARCHAR(40) NOT NULL,
	snmp_version VARCHAR(20) NOT NULL,
	snmp_community NVARCHAR(20) NOT NULL,
	snmp_port INT DEFAULT 161 NOT NULL,
	is_active BIT DEFAULT 1 NOT NULL,
);

ALTER TABLE CU
ADD CONSTRAINT FK_CU_FLOOR_FLOORID
FOREIGN KEY (floor_id)
REFERENCES FLOOR (floor_id);

ALTER TABLE CU DROP CONSTRAINT FK_CU_FLOOR_FLOORID

CREATE TABLE DISTRIBUTION_BOARD(
	db_id BIGINT IDENTITY PRIMARY KEY,
	db_name NVARCHAR(40) UNIQUE NOT NULL,
	floor_id BIGINT NOT NULL,
	row_db BIGINT NOT NULL,
	col_db BIGINT NOT NULL,
	status_db NVARCHAR(20) NULL,
	db_note NVARCHAR(255) NULL,
);

DROP TABLE DISTRIBUTION_BOARD;
SELECT*FROM DISTRIBUTION_BOARD;

--DELETE FROM DISTRIBUTION_BOARD WHERE db_id = 8;
select floor_id from DISTRIBUTION_BOARD where floor_id = 1;

ALTER TABLE DISTRIBUTION_BOARD
ADD CONSTRAINT FK_DB_FLOOR_FLOORID
FOREIGN KEY (floor_id)
REFERENCES FLOOR (floor_id);

ALTER TABLE DISTRIBUTION_BOARD DROP CONSTRAINT FK_DB_FLOOR_FLOORID

CREATE TABLE CONNECTION_LINES (
	conn_id BIGINT IDENTITY PRIMARY KEY,
	conn_name NVARCHAR(20) UNIQUE NOT NULL,
)
SELECT *FROM CONNECTION_LINES
DROP TABLE CONNECTION_LINES

INSERT INTO CONNECTION_LINES VALUES (N'4N-1-1');
INSERT INTO CONNECTION_LINES VALUES (N'4N-1-2');
INSERT INTO CONNECTION_LINES VALUES (N'4N-1-3');

CREATE TABLE CONNECTION_LINES_RACK (
	conn_name NVARCHAR(20) NOT NULL,
	rack_name NVARCHAR(20) NOT NULL,
	PRIMARY KEY (conn_name, rack_name),
)

DROP TABLE CONNECTION_LINES_RACK
SELECT*FROM CONNECTION_LINES_RACK

INSERT INTO CONNECTION_LINES_RACK VALUES (N'4N-1-1',N'4-D-10'), (N'4N-1-25',N'4-D-10');

SELECT
    t1.conn_name,
    t2.rack_name
FROM CONNECTION_LINES_RACK t3
JOIN CONNECTION_LINES t1 ON t3.conn_id = t1.conn_id
JOIN RACK t2 ON t3.rack_id = t2.rack_id;



ALTER TABLE CONNECTION_LINES_RACK DROP CONSTRAINT FK_CONNECTION_LINES_RACK_CONN;

ALTER TABLE CONNECTION_LINES_RACK
ADD CONSTRAINT FK_CONNECTION_LINES_RACK_CONN
FOREIGN KEY (conn_id)
REFERENCES CONNECTION_LINES (conn_id);

ALTER TABLE CONNECTION_LINES_RACK
ADD CONSTRAINT FK_CONNECTION_LINES_RACK_RACK
FOREIGN KEY (rack_id)
REFERENCES RACK (rack_id);

CREATE TABLE CONNECTION_LINES_WORKDESK (
	conn_id BIGINT NOT NULL,
	workdesk_id BIGINT NOT NULL,
)
CREATE TABLE CONNECTION_LINES_DB (
	conn_id BIGINT NOT NULL,
	db_id BIGINT NOT NULL,
)
--------------------------------------------------------------------------------------
CREATE TABLE RACK(
	rack_id BIGINT IDENTITY PRIMARY KEY,
	rack_name NVARCHAR(20) UNIQUE NOT NULL,
	floor_id BIGINT NOT NULL,
	zone_id BIGINT NULL,
	row_rack BIGINT NOT NULL,
	col_rack BIGINT NOT NULL,
	status_db NVARCHAR(20) NULL,
	rack_note NVARCHAR(255) NULL,
);
DROP TABLE RACK
SELECT * FROM RACK;



select*from RACK 
ALTER TABLE RACK
ADD CONSTRAINT FK_RACK_FLOOR_FLOORID
FOREIGN KEY (floor_id)
REFERENCES FLOOR (floor_id);

ALTER TABLE RACK DROP CONSTRAINT FK_RACK_FLOOR_FLOORID
------------------------------------------------------------------------------------------------
CREATE TABLE WORKDESKS(
	workdesk_id BIGINT IDENTITY PRIMARY KEY,
	workdesk_name NVARCHAR(50) UNIQUE NOT NULL,
	workdesk_type NVARCHAR(50) NOT NULL,-- ??????????????
	floor_id BIGINT NOT NULL,
	zone_id BIGINT NOT NULL,
	row_workdesk BIGINT NOT NULL,
	col_workdesk BIGINT NOT NULL,
	status_workdesk NVARCHAR(20) NULL,
	workdesk_note NVARCHAR(255) NULL,
);
DROP TABLE WORKDESKS
SELECT *FROM WORKDESKS

INSERT INTO WORKDESKS VALUES (N'?????', N'????',1,2,32,58);

ALTER TABLE WORKDESKS
ADD CONSTRAINT FK_WORKDESKS_FLOOR_FLOORID
FOREIGN KEY (floor_id)
REFERENCES FLOOR (floor_id);



ALTER TABLE WORKDESKS DROP CONSTRAINT FK_WORKDESKS_FLOOR_FLOORID

CREATE TABLE VOLTAGES (
	volt_id BIGINT IDENTITY PRIMARY KEY,
	volt_type NVARCHAR(20) NOT NULL,
	ampe NVARCHAR(20) NOT NULL,
)
SELECT*FROM VOLTAGES;
INSERT INTO VOLTAGES VALUES (N'100V', N'20A');
INSERT INTO VOLTAGES VALUES (N'200V', N'20A');
INSERT INTO VOLTAGES VALUES (N'200V', N'30A');

CREATE TABLE VOLTAGES_RACK (
	volt_id BIGINT NOT NULL,
	rack_id BIGINT NOT NULL,
	PRIMARY KEY(volt_id, rack_id),
)

INSERT INTO VOLTAGES_RACK VALUES (1,10), (1, )

CREATE TABLE VOLTAGES_WORKDESK (
	volt_id BIGINT NOT NULL,
	workdesk_id BIGINT NOT NULL,
	PRIMARY KEY(volt_id, workdesk_id),
)

CREATE TABLE CU_INFO (
	cu_id BIGINT NOT NULL,
	references_volt DECIMAL(10,3) NULL,
	references_cos DECIMAL(10,3) NULL,
	load_min DECIMAL(10,3) NULL,
	load_max DECIMAL(10,3) NULL,
)

CREATE TABLE OID_OBJECT_TYPE (
	oid VARCHAR(200) PRIMARY KEY,
	name NVARCHAR(50) NOT NULL,
	datatype NVARCHAR(255) NULL,
	unit NVARCHAR(10) NULL,
	status NVARCHAR(20) NULL,
	oid_des NVARCHAR(255) NULL,

)

CREATE TABLE CU_THRESHOLDS (
	cu_id BIGINT NOT NULL,
	oid VARCHAR(200) NOT NULL,
	range_min DECIMAL(10,3) NULL,
	range_max DECIMAL(10,3) NULL,
	low_alarm DECIMAL(10,3) NULL,
	low_caution DECIMAL(10,3) NULL,
	high_caution DECIMAL(10,3) NULL,
	high_alarm DECIMAL(10,3) NULL,
	high_hyst DECIMAL(10,3) NULL,
	low_hyst DECIMAL(10,3) NULL,
)

CREATE TABLE CU_METRIC (
	metric_id BIGINT IDENTITY PRIMARY KEY,
	cu_id BIGINT NOT NULL,
	oid VARCHAR(200) NOT NULL,
	current_value DECIMAL(10,3) NULL,
	value_text VARCHAR(40) NOT NULL,
	ts DATETIME2(3) NULL,
)

CREATE TABLE ALERTS (
	alert_id BIGINT PRIMARY KEY,
	cu_id BIGINT NOT NULL,
	db_id BIGINT NULL,
	rack_id BIGINT NULL,
	workdesk_id BIGINT NULL,
	alert_type NVARCHAR(255) NULL,
	severity NVARCHAR(255) NULL,
	oid VARCHAR(200) NOT NULL,
	value NVARCHAR(255) NULL,
	description NVARCHAR(255) NULL,
)


---------------------------------------------------------------

CREATE TABLE DB_RACK_MAP(
	rack_id BIGINT NOT NULL,
	db_id BIGINT NOT NULL,
	PRIMARY KEY (rack_id, db_id),
);

INSERT INTO DB_RACK_MAP VALUES ()
ALTER TABLE DB_RACK_MAP
ADD CONSTRAINT FK_RACK_DB_RACK_MAP
FOREIGN KEY (rack_id)
REFERENCES RACK (rack_id);

ALTER TABLE DB_RACK_MAP
ADD CONSTRAINT FK_DB_DB_RACK_MAP
FOREIGN KEY (db_id)
REFERENCES DISTRIBUTION_BOARD (db_id);

ALTER TABLE DB_RACK_MAP DROP CONSTRAINT FK_RACK_DB_RACK_MAP
ALTER TABLE DB_RACK_MAP DROP CONSTRAINT FK_DB_DB_RACK_MAP

CREATE TABLE CU_DB_MAP(
	cu_id BIGINT NOT NULL,
	db_id BIGINT NOT NULL,
	PRIMARY KEY (cu_id, db_id),
);
ALTER TABLE CU_DB_MAP
ADD CONSTRAINT FK_CU_CU_DB_MAP
FOREIGN KEY (cu_id)
REFERENCES CU (cu_id);

ALTER TABLE CU_DB_MAP
ADD CONSTRAINT FK_DB_CU_DB_MAP
FOREIGN KEY (db_id)
REFERENCES DISTRIBUTION_BOARD (db_id);

ALTER TABLE CU_DB_MAP DROP CONSTRAINT FK_CU_CU_DB_MAP
ALTER TABLE CU_DB_MAP DROP CONSTRAINT FK_DB_CU_DB_MAP

CREATE TABLE DB_WORKDESK_MAP(
	workdesk_id BIGINT NOT NULL,
	db_id BIGINT NOT NULL,
	PRIMARY KEY (workdesk_id, db_id),
);

ALTER TABLE DB_WORKDESK_MAP
ADD CONSTRAINT FK_WORKDESK_DB_WORKDESK_MAP
FOREIGN KEY (workdesk_id)
REFERENCES WORKDESKS (workdesk_id);

ALTER TABLE DB_WORKDESK_MAP
ADD CONSTRAINT FK_DB_DB_WORKDESK_MAP
FOREIGN KEY (db_id)
REFERENCES DISTRIBUTION_BOARD (db_id);

ALTER TABLE DB_WORKDESK_MAP DROP CONSTRAINT FK_WORKDESK_DB_WORKDESK_MAP
ALTER TABLE DB_WORKDESK_MAP DROP CONSTRAINT FK_DB_DB_WORKDESK_MAP

----------



/*ALTER TABLE child_table
ADD CONSTRAINT constraint_name
FOREIGN KEY (foreign_key_column)
REFERENCES parent_table (primary_key_column);
*/

SELECT * FROM sys.dm_exec_connections WHERE local_net_address IS NOT NULL;



